// <auto-generated />
namespace Sib_Sistema_Imobiliario_Blockchain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class semData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(semData));
        
        string IMigrationMetadata.Id
        {
            get { return "202005070001399_semData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
